### ISSUE TITLE
2nd-order nesting fails to generate correct type string

### ISSUE THREAD

**Issue by alex-miller-0** [Mrtenz/eip-712#35]
Maybe related to #34

I am able to successfully test several payloads, but all payloads with 2nd-order nesting fail, specifically meaning they do not match the hashes from [`ethers-eip712`](https://github.com/0xsequence/ethers-eip712), which are correct.

I think there may be multiple issues, but the first one I found is that `encodeType` is not working properly for 2nd-order nesting. For example, I am using the following message:

```
const msg = {
  types: {
    EIP712Domain: [
      { name: 'name', type: 'string' },
      { name: 'version', type: 'string' },
      { name: 'chainId', type: 'uint256' },
      { name: 'verifyingContract', type: 'address' }
    ],
    Wallet: [
      { name: 'balance', type: 'Balance' },
    ],
    Person: [
      { name: 'wallet', type: 'Wallet' }
    ],
    Mail: [
      { name: 'from', type: 'Person' },
    ],
    Balance: [
      { name: 'currency', type: 'string' }
    ]
  },
  primaryType: 'Mail',
  domain: {
    name: 'Ether Mail',
    version: '1',
    chainId: 12,
    verifyingContract: '0xCcCCccccCCCCcCCCCCCcCcCccCcCCCcCcccccccC'
  },
  message: {
    from: {
      wallet: {
        balance: {
          currency: 'ETH',
        }
      },
    },
  }
};
```

Here are the full type names I get for `primaryType`:

* `ethers-eip712` (correct): `Mail(Person from)Person(Wallet wallet)Wallet(Balance balance)Balance(string currency)`
* `eip-712` (incorrect): `Mail(Person from)Balance(string currency)Person(Wallet wallet)Wallet(Balance balance)`

It appears there is an edge case somewhere in your `encodeType` function, which differs significantly from [that of `ethers-eip712`](https://github.com/0xsequence/ethers-eip712/blob/master/src/typed-data.ts#L122). Note that payloads with 1st order nesting work just fine.

**Comment by Mrtenz** [comment]
Looking into this, thanks for the issue report!

**Comment by Mrtenz** [comment]
After some digging into it, it appears that the type generated by `ethers-eip712` is incorrect. The EIP-712 specification mentions:

> If the struct type references other struct types (and these in turn reference even more struct types), then the set of referenced struct types is collected, sorted by name and appended to the encoding

So all the dependencies are sorted alphabetically, not just direct dependencies of a struct (as done in `ethers-eip712` it seems). I verified that this matches the [implementation by MetaMask](https://github.com/MetaMask/eth-sig-util/blob/73ace3309bf4b97d901fb66cd61db15eede7afe9/src/sign-typed-data.ts#L271-L292) and [the reference implementation mentioned in the EIP-712 specification](https://github.com/ethereum/EIPs/blob/ecb2eb89b0610428c1f6b2e25fdae173fa479cc3/assets/eip-712/Example.js#L64-L76). Both generate the following (apparently correct) type:

```
Mail(Person from)Balance(string currency)Person(Wallet wallet)Wallet(Balance balance)
```

**Comment by alex-miller-0** [comment]
Interesting! Thanks for pointing this out
